@StockScalping_HostAddress = http://localhost:5048

GET {{StockScalping_HostAddress}}/Account/profile
Accept: application/json

###

GET {{StockScalping_HostAddress}}/Stock/prices
Accept: application/json

###

GET {{StockScalping_HostAddress}}/Stock/holdings
Accept: application/json

###

GET {{StockScalping_HostAddress}}/Order
Accept: application/json

###

GET {{StockScalping_HostAddress}}/Scalping/status
Accept: application/json

###
